# Generated by Django 5.1.1 on 2024-09-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
