# Generated by Django 5.1.1 on 2024-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_file',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
