# Generated by Django 5.1.1 on 2024-10-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_profile_picture_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('guest', models.CharField(max_length=255)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('who_win', models.CharField()),
                ('game_type', models.CharField(max_length=255)),
            ],
        ),
    ]
