# Generated by Django 5.1.1 on 2024-10-03 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='users.match'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matches',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
