# Generated by Django 5.1.1 on 2024-10-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_matches_match_alter_matches_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
