# Generated by Django 5.1.1 on 2024-10-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_match_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='guest',
            new_name='enemy',
        ),
    ]
