# Generated by Django 5.1.1 on 2024-10-03 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_guest_match_enemy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='enemy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
