# Generated by Django 5.1.1 on 2024-10-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_match_enemy_alter_match_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='match',
        ),
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='matches',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Matches',
        ),
    ]
