# Generated by Django 5.1.1 on 2024-10-08 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guest',
            field=models.ManyToManyField(blank=True, related_name='guest', to=settings.AUTH_USER_MODEL),
        ),
    ]
