# Generated by Django 5.1.1 on 2024-10-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_match_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='quest_score',
            new_name='guest_score',
        ),
    ]
