# Generated by Django 5.1.1 on 2024-10-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_quest_score_match_guest_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played_time',
            field=models.IntegerField(default=0),
        ),
    ]
