# Generated by Django 5.1.1 on 2024-11-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_matchrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchRequest',
        ),
    ]
